server:
  port: 9000
management:
  port: 9001
spring:
  application:
    name: omaha
  cloud:
    config:
      uri: http://localhost:8888  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  